language: java
deploy:
  provider: heroku
  api_key:
    secure: l6PzF14eM2SQ7Yqv96llgxixBIzvWUqL5GKr/8hvc5HdP6fdMlRCAtgLHwGD+vHyeACYZMRSpB2omgR0Xei3zBMnyEoHiQ+0HpfqmjLDU8Thqj0L1O8EyXKcYknvphAhnY1llY5PCOQETId1d9/6aUS+1gRn6/a+knSDf7gS5H7ObvIW2Gv0e+C/dBH4cHpcm24mp7hkZ/ZO1ESVmgix0QDFGCRR0W93A4H8ivHWYBYP4CDmCDujusILqbnwbUYJlXWRfwlYQdODpVxFKkTkc7x+2xk0SJ9w7HCgsqg0YnA0cfptKTTla1q32+Wljnky/mHSphKd+CCpIhGfiUW4/kedRXJf6LIImEi2rs0CEEZz7iTONNSsYbX9amZFJyMk0Xcfkq8uV6DRqrTwdkpG9xaYHvhDeMrXBFB28sHi7wLJpejVr8WQdi8eKwSUYMeIYOnKQmZCs3EEh69cvpdLmKiciEgwbuUBIAOiLPKjTlOlFF/mDAc6u759FODd532gCJc2pJzrqWkTzHzrDDvWh7muqT30iV1ACUoQ6KFOyfLjzj3iDUknmeet9586ptPHlRZv/Zg2GDm0Hj40La0iTKe2NGooCKnL91hlJdTWTwvz7ThG+UFxOQzmkUUj1JxvM9ZbR/C5I4udeskCWHnYR8vTqVZJiGdeQs9HHIN+0vE=
  app: bath-climate
  on:
    repo: Rshalika/iot-bath-climate
